from defs import *
import random
import string 
import os.path
from sys import exit
from time import sleep

print("Welcome in PassHelper!")
print("Author: Piotr Ptaszek\n")
print("This program will help you strengthen your password proposal \nto make it stronger \nor generate you a new password.\n")

pas = []
answer = input("What do you want to do:\n1 - help to strengthen your password proposal\n2 - generate password\nI want this program to: ")
if (answer == '1'):
    while True:
        password = input("Enter proposed password: ")
        pas.append(password)
        pas[0] = password
        if validate_password(password):
            print("\nYour password is correct.")
            break
    yorn = input(print("Do you want to save your new password in *.txt file? (y for yes, n for no): "))
    if yorn == "y":
        name_of_file = input("What is the name of the file: ")
        completeName = os.path.join(os.path.expandvars("%userprofile%"), "Desktop", name_of_file+".txt")
        at = "Your new password is: " + pas[0] + " helped by PassHelper"
        file1 = open(completeName, "w")
        file1.write(at)
        file1.close()
        print("Your password is on desktop")
        print("Program will close in 3 secounds")
        sleep(3)
        exit(0)
    elif yorn == "n":
        print("Program will close in 3 secounds")
        sleep(3)
        exit(0)
    else:
        print("Wrong chose :(")
        print("Program will close in 3 secounds")
        sleep(3)
        exit(0)
        
elif answer == '2':
    numbers = random.randrange(100, 999)
    string.letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()[}]{<>.,?/'
    answ = int(input(print("How many characters do you want your password to have? (min. 8): ")))
    if answ >= 8:
        letters_section = ''.join(random.choice(string.letters) for _ in range(answ))
        passw = str(numbers) + letters_section
        print("Your generated password is: " + passw + "\n")
        yngp = input(print("Do you want to save your new password in *.txt file? (y for yes, n for no): "))
        if yngp == "y":
            name_of_file = input("What is the name of the file: ")
            completeName = os.path.join(os.path.expandvars("%userprofile%"), "Desktop", name_of_file+".txt")
            at = "Your new password is: " + passw + " generated by PassHelper"
            file1 = open(completeName, "w")
            file1.write(at)
            file1.close()
            print("Your password is on desktop")
            print("Program will close in 3 secounds")
            sleep(3)
            exit(0)
        elif yngp == "n":
            print("Program will close in 3 secounds")
            sleep(3)
            exit(0)
        else:
            print("Wrong chose :(")
            print("Program will close in 3 secounds")
            sleep(3)
            exit(0)
    else:
        print("Wrong chose :(")
        print("Program will close in 3 secounds")
        sleep(3)
        exit(0)

else:
    print("Wrong chose :(")
    print("Program will close in 3 secounds")
    sleep(3)
    exit(0)
